version: '3.7'
services:
  account-service-dev:
    image: 211020/mhmarket-account:latest
    container_name: account-service
    ports:
      - "9565:9565"
    environment:
      CLOUD_CONFIG_URL: http://103.162.20.152:8082
      CLOUD_CONFIG_PROFILE: dev
      CLOUD_CONFIG_LABEL: master
    restart: unless-stopped
    networks:
      - mh-network
    dns:
      - 103.162.20.4
      - 8.8.8.8
networks:
  mh-network:
    driver: bridge